volumes:
  letsencrypt:

networks:
  frontend: # entry point
    name: frontend
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.1.0/24
  mgmt_tier: #mgmt containers
    name: mgmt_tier
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.23.2.0/24
  download_tier: #application and download services
    name: download_tier
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.23.3.0/24

secrets:
  openvpn_creds:
    file: /opt/secrets/openvpn-credentials.txt

services:
#reverse proxy solution
  traefik:
    image: docker.io/library/traefik:v3.7
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TIMEZONE}
    command:
      - --api.insecure=true #troubleshooting
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --log.Level=info
      - --accesslog=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --providers.docker.network=frontend
      - --entrypoints.websecure.address=:443
      - --providers.docker.exposedbydefault=false
      - --certificatesResolvers.letsencrypt.acme.email=${EMAIL}
      - --certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.letsencrypt.acme.tlsChallenge=true # used during the challenge, default is normally to use HTTP.
      #enable below URL when testing otherwise you hit letsencrypt limits around generating certs
      - --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
    networks:
      - frontend
    volumes:
      - letsencrypt:/letsencrypt/
      - /run/user/${USER_PID}/podman/podman.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=true
      # 1. Secure Traefik API (needed for dashboard)
      - traefik.http.routers.traefik-api.rule=Host(`${DOMAIN}`)&&PathPrefix(`/api`)
      - traefik.http.routers.traefik-api.entrypoints=websecure
      - traefik.http.routers.traefik-api.service=api@internal
      - traefik.http.routers.traefik-api.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-api.tls=true
      # 1.5 Secure Traefik dashboard && not require extra / after /dashboard - will make it get a bit funky and add /dashboard/#/ but works!
      - traefik.http.routers.traefik-dashboard.rule=Host(`${DOMAIN}`)&&PathPrefix(`/dashboard`)
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.middlewares.traefik-dashboard-chain.chain.middlewares=strip-prefix-1,strip-prefix-2
      - traefik.http.routers.traefik-dashboard.middlewares=traefik-dashboard-chain
      - traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-dashboard.tls=true
      # 3. Strip /url or /url/ prefixes
      # an issue occurs when chaining qbt with authelia where you need to refresh to continue. No issue with portainer
      # https://github.com/authelia/authelia/issues/372
      # prefixes taken from https://www.reddit.com/r/Traefik/comments/ezj88o/path_based_redirection_pain_and_suffering_v2/
      - traefik.http.middlewares.strip-prefix-1.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$
      - traefik.http.middlewares.strip-prefix-1.redirectregex.replacement=$${1}/
      - traefik.http.middlewares.strip-prefix-1.redirectregex.permanent=true
      - traefik.http.middlewares.strip-prefix-2.stripprefixregex.regex=/[a-z0-9_]+
    restart: always

#movie manager
  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    environment:
      - PUID=${USER_PID}
      - PGID=${USER_PID}
      - TZ=${TIMEZONE}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7878/ping || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - download_tier
      - frontend
    volumes:
      - ${CONFIG}/radarr:/config
      - ${CONTENT}/downloads/torrents:/data/downloads/torrents
      - ${CONTENT}/downloads/usenet/complete:/downloads
      - ${CONTENT}/media/movies:/data/media/movies
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`${DOMAIN}`)&&PathPrefix(`/radarr`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.tls.certresolver=letsencrypt
      - traefik.http.routers.radarr.tls=true
    restart: always

#tv show manager
  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    environment:
      - PUID=${USER_PID}
      - PGID=${USER_PID}
      - TZ=${TIMEZONE}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8989/ping || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - download_tier
      - frontend
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${CONTENT}/downloads/torrents:/data/downloads/torrents
      - ${CONTENT}/downloads/usenet/complete:/downloads
      - ${CONTENT}/media/tv:/data/media/tv
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`${DOMAIN}`)&&PathPrefix(`/sonarr`)
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.tls.certresolver=letsencrypt
      - traefik.http.routers.sonarr.tls=true
    restart: always

# Cloudflare bypass
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
      - TZ=${TIMEZONE}
    networks:
      - frontend
    labels:
      - traefik.enable=false #dump less stuff into logs if you debug
    restart: always

# Indexer for torrents and nzb
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    environment:
      - PUID=${USER_PID}
      - PGID=${USER_PID}
      - TZ=${TIMEZONE}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9696/ping || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - download_tier
      - frontend
    volumes:
      - ${CONFIG}/prowlarr:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`${DOMAIN}`)&&PathPrefix(`/prowlarr`)
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.tls.certresolver=letsencrypt
      - traefik.http.routers.prowlarr.tls=true
    restart: always

#download usenet files
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${USER_PID}
      - PGID=${USER_PID}
      - TZ=${TIMEZONE}
    networks:
      - download_tier
      - frontend
    volumes:
      - ${CONFIG}/sabnzbd:/config
      - ${CONTENT}/downloads/usenet/incomplete:/incomplete-downloads
      - ${CONTENT}/downloads/usenet/complete:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.rule=Host(`${DOMAIN}`)&&PathPrefix(`/sabnzbd`)
      - traefik.http.routers.sabnzbd.entrypoints=websecure
      - traefik.http.routers.sabnzbd.tls.certresolver=letsencrypt
      - traefik.http.routers.sabnzbd.tls=true
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
    restart: always

#download torrents
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    secrets:
      - openvpn_creds
    healthcheck:
      interval: 5s
      start_period: 10s
    cap_add:
      - NET_ADMIN
      - NET_RAW
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - PUID=${USER_PID}
      - PGID=${USER_PID}
      - TZ=${TIMEZONE}
      - CREATE_TUN_DEVICE=false
      #- LOCAL_NETWORK=172.23.3.0/24
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=false
      - TRANSMISSION_RPC_ENABLE_CSRF=false
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/watch
      - TRANSMISSION_DOWNLOAD_DIR=/data/downloads/torrents
      - TRANSMISSION_INCOMPLETE_DIR=/data/downloads/torrents/incomplete
      - TRANSMISSION_WEB_UI=transmission-web-control
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=**None**
      - OPENVPN_PASSWORD=**None**
      - NORDVPN_COUNTRY=AU
      - NORDVPN_CATEGORY=P2P
      - NORDVPN_PROTOCOL=udp
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - WEBPROXY_ENABLED=false
    devices:
      - /dev/net/tun
    networks:
      - download_tier
      - frontend
    volumes:
      - ${CONTENT}/downloads/torrents:/data/downloads/torrents #keeps usenet and torrent downloads seperated
      # plus transmission makes its own completed & incomplete subfolders
      - ${CONTENT}/downloads/blackhole:/watch
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.rule=Host(`${DOMAIN}`)&&PathPrefix(`/transmission`)
      - traefik.http.routers.transmission.entrypoints=websecure
      - traefik.http.routers.transmission.tls.certresolver=letsencrypt
      - traefik.http.routers.transmission.tls=true
      - traefik.http.routers.transmission.service=transmission
      - traefik.http.services.transmission.loadbalancer.server.scheme=http
      - traefik.http.services.transmission.loadbalancer.server.port=9091
    restart: always

  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${USER_PID}
      - PGID=${USER_PID}
      - TZ=${TIMEZONE}
    networks:
      - frontend
    volumes:
      - ${CONFIG}/jellyfin:/config
      - ${CONTENT}/media:/media:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_DOMAIN}`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls.certresolver=letsencrypt
      - traefik.http.routers.jellyfin.tls=true
    restart: always
